import { defineConfig } from "drizzle-kit";
export default defineConfig({
  schema: [
    "./drizzle/schema.ts",
    "./drizzle/schema-gps-models.ts",
    "./drizzle/financial-schema.ts",
    "./drizzle/exchange-schema.ts",
    "./drizzle/kyc-schema.ts",
    "./drizzle/supply-chain-schema.ts",
    "./drizzle/cooperative-schema.ts",
    "./drizzle/credit-scoring-schema.ts",
    "./drizzle/traceability-schema.ts",
    "./drizzle/platform-extensions-schema.ts",
    "./drizzle/schema-platform-extended.ts",
    "./drizzle/ledger-schema.ts",
    "./drizzle/disbursement-schema.ts",
    "./drizzle/loan-application-schema.ts",
    "./drizzle/notification-schema.ts",
    "./drizzle/user-preferences-schema.ts",
    "./drizzle/user-journey-schema.ts",
    "./drizzle/agent-productivity-schema.ts",
    "./drizzle/alert-thresholds-schema.ts",
    "./drizzle/sms-logs-schema.ts",
    "./drizzle/sms-responses-schema.ts",
    "./drizzle/sms-templates-schema.ts",
    "./drizzle/schema-dairy.ts",
    "./drizzle/schema-ml-models.ts",
    "./drizzle/schema-spatial-analysis.ts",
    "./drizzle/schema-postgis.ts",
    "./drizzle/schema-subsidy.ts",
    "./drizzle/schema-agricultural-intelligence.ts",
    "./drizzle/schema-export-schedules.ts",
    "./drizzle/precision-agriculture-schema.ts",
    "./drizzle/distributor-schema.ts",
    "./drizzle/erpnext-schema.ts",
  ],
  out: "./drizzle/migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL!,
  },
});
