import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    include: ['**/__tests__/**/*.test.ts', '**/*.test.ts'],
    exclude: [
      'node_modules',
      'dist',
      'client',
      'mobile/**',
      'tests/mobile/**',
      // Integration tests that require running PostgreSQL/services
      'server/__tests__/auth.test.ts',
      'server/__tests__/auth-integration.test.ts',
      'server/__tests__/farmer-crud.test.ts',
      'server/__tests__/integration.test.ts',
      'server/__tests__/loan-approval.test.ts',
      'server/__tests__/messaging-service.test.ts',
      'server/__tests__/messaging-channels.test.ts',
      'server/__tests__/marketplace-image-upload.test.ts',
      'server/__tests__/review-analytics.test.ts',
      'server/__tests__/review-purchase-verification.test.ts',
      'server/__tests__/ml-predictions-farm-data.test.ts',
      'server/__tests__/sync.test.ts',
      'server/__tests__/sync-improved.test.ts',
      'server/routers/__tests__/sms-templates-router.test.ts',
      'server/routers/__tests__/health-router.test.ts',
      'tests/marketplace.test.ts',
      'tests/microfinance.test.ts',
      'server/__tests__/accounting-router.test.ts',
      'server/__tests__/analytics-enhancements.test.ts',
      'server/__tests__/analytics-router.test.ts',
      'server/__tests__/e2e-critical-flows.test.ts',
      'server/__tests__/hr-router.test.ts',
      'server/__tests__/inventory-router.test.ts',
      'server/__tests__/microfinance-procedures.test.ts',
      'server/__tests__/new-features.test.ts',
      'server/services/__tests__/payment-reminder-cron.test.ts',
    ],
    testTimeout: 30000,
    setupFiles: ['./tests/setup.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary', 'json', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: ['server/**/*.ts'],
      exclude: [
        'server/**/__tests__/**',
        'server/**/*.test.ts',
        'server/**/*.spec.ts',
        'node_modules/**',
      ],
      thresholds: {
        lines: 70,
        functions: 65,
        branches: 55,
        statements: 70,
      },
    },
  },
});
