apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: postgres-binding
spec:
  type: bindings.postgresql
  version: v1
  metadata:
  - name: url
    value: "host=postgres user=postgres password=postgres dbname=farmer_db port=5432 sslmode=disable"
  - name: maxConns
    value: "10"
