http.host: "0.0.0.0"
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["http://opensearch:9200"]
xpack.monitoring.elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
xpack.monitoring.elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
