apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmconnect-app
  namespace: farmconnect
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: app
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
