apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: farmconnect

resources:
  - ../../base
  - ../../monitoring/prometheus-alerts.yaml
  - ../../monitoring/prometheus-config.yaml
  - ../../monitoring/grafana-dashboard.json
  - ../../monitoring/otel-collector.yaml
  - ../../monitoring/fluentd-config.yaml
  - ../../hardening/hpa.yaml
  - ../../hardening/backup-cronjobs.yaml
  - ../../hardening/pod-disruption-budgets.yaml
  - ../../hardening/keda-scaled-objects.yaml
  - ../../istio/service-mesh.yaml

patchesStrategicMerge:
  - app-patch.yaml
  - ../../hardening/graceful-shutdown-patch.yaml

commonLabels:
  environment: production
