"""
YOLOv8 Training Pipeline for Nigerian Produce Detection & Classification.

Fine-tunes YOLOv8 on Nigerian agricultural produce for:
1. Object detection — localize produce in inspection images
2. Classification — identify crop type (cassava, rice, cocoa, etc.)
3. Defect detection — detect and locate defects (mold, rot, insects, etc.)

Usage:
    # Train produce detector
    python training/train_yolov8.py --task detect --data data/datasets/produce_detect.yaml --epochs 100

    # Train grade classifier
    python training/train_yolov8.py --task classify --data data/datasets/produce_classify/ --epochs 50

    # Train defect detector
    python training/train_yolov8.py --task detect --data data/datasets/defect_detect.yaml --epochs 150

    # Export to ONNX for inference service
    python training/train_yolov8.py --export --model runs/detect/best.pt --format onnx
"""

import argparse
import json
import os
import shutil
import random
from pathlib import Path
from typing import Optional

# ── Dataset Preparation ──────────────────────────────────────────────────

PRODUCE_CLASSES = [
    "cassava", "rice", "cocoa", "yam", "groundnut", "maize", "millet",
    "sorghum", "plantain", "tomato", "pepper", "oil_palm", "cowpea",
    "soybean", "ginger", "sesame", "cashew", "shea_nut", "watermelon",
    "okra", "onion",
]

DEFECT_CLASSES = [
    "rot", "mold", "bruising", "insect_damage", "discoloration",
    "soft_spots", "broken_grains", "foreign_matter", "cracking",
    "pest_damage", "aflatoxin", "weevil_holes", "over_ripeness",
    "sprouting", "sunscald",
]

GRADE_CLASSES = ["grade_A", "grade_B", "grade_C", "grade_D", "reject"]


def create_detection_yaml(output_path: str, dataset_root: str, classes: list[str], task: str = "produce"):
    """Create YOLO dataset YAML config file."""
    yaml_content = f"""# FarmConnect Nigerian Produce {task.title()} Detection Dataset
# Auto-generated by training pipeline

path: {os.path.abspath(dataset_root)}
train: images/train
val: images/val
test: images/test

# Number of classes
nc: {len(classes)}

# Class names
names:
"""
    for i, cls in enumerate(classes):
        yaml_content += f"  {i}: {cls}\n"

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(yaml_content)
    print(f"Dataset YAML created: {output_path}")
    return output_path


def prepare_dataset_structure(
    source_dir: str,
    output_dir: str,
    train_ratio: float = 0.7,
    val_ratio: float = 0.2,
    test_ratio: float = 0.1,
    seed: int = 42,
):
    """
    Convert COCO-format synthetic dataset into YOLO format.

    YOLO format:
        images/train/  images/val/  images/test/
        labels/train/  labels/val/  labels/test/

    Each label file: one line per object:
        class_id cx cy w h  (normalized 0-1)
    """
    random.seed(seed)
    source = Path(source_dir)
    output = Path(output_dir)

    # Load COCO annotations
    ann_path = source / "annotations.json"
    if not ann_path.exists():
        print(f"No annotations.json found in {source_dir}")
        print("Run synthetic_generator.py first to create the dataset")
        return

    with open(ann_path) as f:
        coco = json.load(f)

    # Build category lookup
    cat_lookup = {cat["id"]: cat["name"] for cat in coco["categories"]}
    class_list = [cat["name"] for cat in coco["categories"] if not cat["name"].startswith("defect_")]
    class_to_id = {name: i for i, name in enumerate(class_list)}

    # Build image annotation lookup
    img_anns = {}
    for ann in coco["annotations"]:
        img_id = ann["image_id"]
        if img_id not in img_anns:
            img_anns[img_id] = []
        img_anns[img_id].append(ann)

    # Split images
    images = coco["images"]
    random.shuffle(images)
    n = len(images)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)

    splits = {
        "train": images[:n_train],
        "val": images[n_train:n_train + n_val],
        "test": images[n_train + n_val:],
    }

    # Create directory structure
    for split in ["train", "val", "test"]:
        (output / "images" / split).mkdir(parents=True, exist_ok=True)
        (output / "labels" / split).mkdir(parents=True, exist_ok=True)

    total_copied = 0
    for split, split_images in splits.items():
        for img in split_images:
            img_file = source / img["file_name"]
            if not img_file.exists():
                # Check for .json placeholder
                json_file = img_file.with_suffix(".json")
                if json_file.exists():
                    # Copy placeholder metadata
                    dst = output / "images" / split / img_file.name
                    shutil.copy2(json_file, dst.with_suffix(".json"))
                continue

            # Copy image
            dst = output / "images" / split / img_file.name
            shutil.copy2(img_file, dst)

            # Create YOLO label file
            label_file = output / "labels" / split / img_file.stem + ".txt"
            anns = img_anns.get(img["id"], [])
            lines = []
            for ann in anns:
                cat_name = cat_lookup.get(ann["category_id"], "")
                if cat_name in class_to_id:
                    cls_id = class_to_id[cat_name]
                    bbox = ann["bbox"]  # [x, y, w, h] in pixels
                    img_w = img["width"]
                    img_h = img["height"]
                    cx = (bbox[0] + bbox[2] / 2) / img_w
                    cy = (bbox[1] + bbox[3] / 2) / img_h
                    w = bbox[2] / img_w
                    h = bbox[3] / img_h
                    lines.append(f"{cls_id} {cx:.6f} {cy:.6f} {w:.6f} {h:.6f}")

            label_path = output / "labels" / split / (img_file.stem + ".txt")
            label_path.write_text("\n".join(lines))
            total_copied += 1

    print(f"Dataset prepared: {total_copied} images across {len(splits)} splits")
    print(f"  Train: {len(splits['train'])}, Val: {len(splits['val'])}, Test: {len(splits['test'])}")

    # Create dataset YAML
    yaml_path = output / "dataset.yaml"
    create_detection_yaml(str(yaml_path), str(output), class_list)
    return str(yaml_path)


def prepare_classification_dataset(source_dir: str, output_dir: str, seed: int = 42):
    """
    Prepare classification dataset (grade classification).

    Structure:
        train/grade_A/  train/grade_B/ ...
        val/grade_A/    val/grade_B/   ...
    """
    random.seed(seed)
    source = Path(source_dir)
    output = Path(output_dir)

    grades = ["A", "B", "C", "D", "reject"]
    total = 0

    for crop_dir in source.iterdir():
        if not crop_dir.is_dir():
            continue
        for grade in grades:
            grade_dir = crop_dir / grade
            if not grade_dir.exists():
                continue
            images = list(grade_dir.glob("*.png")) + list(grade_dir.glob("*.jpg"))
            random.shuffle(images)

            n = len(images)
            n_train = int(n * 0.8)

            class_name = f"grade_{grade}" if grade != "reject" else "reject"

            for i, img in enumerate(images):
                split = "train" if i < n_train else "val"
                dst_dir = output / split / class_name
                dst_dir.mkdir(parents=True, exist_ok=True)
                shutil.copy2(img, dst_dir / img.name)
                total += 1

    print(f"Classification dataset prepared: {total} images")
    return str(output)


# ── Training ─────────────────────────────────────────────────────────────

def train_detector(
    data_yaml: str,
    model_size: str = "m",
    epochs: int = 100,
    batch_size: int = 16,
    image_size: int = 640,
    project: str = "runs/detect",
    name: str = "nigerian_produce",
    pretrained: bool = True,
    device: str = "",
    patience: int = 20,
    augment: bool = True,
):
    """
    Fine-tune YOLOv8 for produce/defect detection.

    Args:
        model_size: n(ano), s(mall), m(edium), l(arge), x(large)
    """
    from ultralytics import YOLO

    model_name = f"yolov8{model_size}.pt" if pretrained else f"yolov8{model_size}.yaml"
    model = YOLO(model_name)

    print(f"\n{'='*60}")
    print(f"Training YOLOv8{model_size} Produce Detector")
    print(f"  Dataset: {data_yaml}")
    print(f"  Epochs: {epochs}")
    print(f"  Batch: {batch_size}")
    print(f"  Image size: {image_size}")
    print(f"  Pretrained: {pretrained}")
    print(f"{'='*60}\n")

    results = model.train(
        data=data_yaml,
        epochs=epochs,
        batch=batch_size,
        imgsz=image_size,
        project=project,
        name=name,
        patience=patience,
        device=device or None,
        # Augmentation
        hsv_h=0.015 if augment else 0,
        hsv_s=0.7 if augment else 0,
        hsv_v=0.4 if augment else 0,
        degrees=10.0 if augment else 0,
        translate=0.1 if augment else 0,
        scale=0.5 if augment else 0,
        shear=2.0 if augment else 0,
        flipud=0.2 if augment else 0,
        fliplr=0.5 if augment else 0,
        mosaic=1.0 if augment else 0,
        mixup=0.1 if augment else 0,
        # Optimization
        optimizer="AdamW",
        lr0=0.001,
        lrf=0.01,
        weight_decay=0.0005,
        warmup_epochs=3,
        # Callbacks
        save=True,
        save_period=10,
        plots=True,
        verbose=True,
    )

    print(f"\nTraining complete. Best model: {project}/{name}/weights/best.pt")
    print(f"Results: mAP50={results.results_dict.get('metrics/mAP50(B)', 'N/A')}")
    return results


def train_classifier(
    data_dir: str,
    model_size: str = "m",
    epochs: int = 50,
    batch_size: int = 32,
    image_size: int = 224,
    project: str = "runs/classify",
    name: str = "nigerian_grade",
    device: str = "",
):
    """Fine-tune YOLOv8 classifier for produce grade classification."""
    from ultralytics import YOLO

    model = YOLO(f"yolov8{model_size}-cls.pt")

    print(f"\n{'='*60}")
    print(f"Training YOLOv8{model_size} Grade Classifier")
    print(f"  Dataset: {data_dir}")
    print(f"  Epochs: {epochs}")
    print(f"{'='*60}\n")

    results = model.train(
        data=data_dir,
        epochs=epochs,
        batch=batch_size,
        imgsz=image_size,
        project=project,
        name=name,
        device=device or None,
        optimizer="AdamW",
        lr0=0.001,
        patience=15,
        plots=True,
    )

    print(f"\nClassifier training complete: {project}/{name}/weights/best.pt")
    return results


def export_model(model_path: str, export_format: str = "onnx", image_size: int = 640):
    """Export trained model for production inference."""
    from ultralytics import YOLO

    model = YOLO(model_path)

    print(f"Exporting {model_path} to {export_format}...")
    exported = model.export(
        format=export_format,
        imgsz=image_size,
        half=True if export_format in ("onnx", "tensorrt") else False,
        dynamic=True if export_format == "onnx" else False,
        simplify=True if export_format == "onnx" else False,
    )

    print(f"Model exported: {exported}")
    return exported


def validate_model(model_path: str, data_yaml: str, image_size: int = 640):
    """Run validation on test set."""
    from ultralytics import YOLO

    model = YOLO(model_path)
    results = model.val(data=data_yaml, imgsz=image_size, split="test")
    print(f"\nValidation Results:")
    print(f"  mAP50: {results.results_dict.get('metrics/mAP50(B)', 'N/A')}")
    print(f"  mAP50-95: {results.results_dict.get('metrics/mAP50-95(B)', 'N/A')}")
    print(f"  Precision: {results.results_dict.get('metrics/precision(B)', 'N/A')}")
    print(f"  Recall: {results.results_dict.get('metrics/recall(B)', 'N/A')}")
    return results


# ── CLI ───────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="YOLOv8 Training Pipeline for Nigerian Produce")

    subparsers = parser.add_subparsers(dest="command", help="Command to run")

    # Prepare dataset
    prep = subparsers.add_parser("prepare", help="Prepare dataset from synthetic images")
    prep.add_argument("--source", type=str, default="data/synthetic", help="Source directory with COCO annotations")
    prep.add_argument("--output", type=str, default="data/datasets/produce_detect", help="Output dataset directory")
    prep.add_argument("--task", type=str, choices=["detect", "classify"], default="detect")

    # Train
    train = subparsers.add_parser("train", help="Train YOLOv8 model")
    train.add_argument("--task", type=str, choices=["detect", "classify"], default="detect")
    train.add_argument("--data", type=str, required=True, help="Dataset YAML or directory")
    train.add_argument("--model", type=str, default="m", help="Model size: n/s/m/l/x")
    train.add_argument("--epochs", type=int, default=100)
    train.add_argument("--batch", type=int, default=16)
    train.add_argument("--imgsz", type=int, default=640)
    train.add_argument("--device", type=str, default="")
    train.add_argument("--name", type=str, default="nigerian_produce")

    # Export
    exp = subparsers.add_parser("export", help="Export trained model")
    exp.add_argument("--model", type=str, required=True, help="Path to .pt model")
    exp.add_argument("--format", type=str, default="onnx", choices=["onnx", "torchscript", "tensorrt", "coreml"])
    exp.add_argument("--imgsz", type=int, default=640)

    # Validate
    val = subparsers.add_parser("validate", help="Validate model on test set")
    val.add_argument("--model", type=str, required=True)
    val.add_argument("--data", type=str, required=True)

    args = parser.parse_args()

    if args.command == "prepare":
        if args.task == "detect":
            prepare_dataset_structure(args.source, args.output)
        else:
            prepare_classification_dataset(args.source, args.output)

    elif args.command == "train":
        if args.task == "detect":
            train_detector(
                data_yaml=args.data,
                model_size=args.model,
                epochs=args.epochs,
                batch_size=args.batch,
                image_size=args.imgsz,
                name=args.name,
                device=args.device,
            )
        else:
            train_classifier(
                data_dir=args.data,
                model_size=args.model,
                epochs=args.epochs,
                batch_size=args.batch,
                image_size=args.imgsz,
                name=args.name,
                device=args.device,
            )

    elif args.command == "export":
        export_model(args.model, args.format, args.imgsz)

    elif args.command == "validate":
        validate_model(args.model, args.data)

    else:
        parser.print_help()
