apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: farmconnect

resources:
  - namespace.yaml
  - configmap.yaml
  - app-deployment.yaml
  - microservices.yaml

commonLabels:
  app.kubernetes.io/part-of: farmconnect-platform
  app.kubernetes.io/managed-by: kustomize
